@echo off
echo Starting Inventory Management System...
echo Starting Backend (FastAPI)...
start "Inventory Backend" call start_server.bat
timeout /t 5 /nobreak
echo Starting Frontend (Streamlit)...
streamlit run frontend.py
